export const theme = {
	light: {
		colors: {
			primary: {
				main: '#9155FD',
				light: '#9E69FD',
				dark: '#6E41C0',
				contrast: '#FFFFFF',
				containedHover: '#804BDF',
				outlinedHover: '#9155FD14',
				outlinedRestingHover: '#9155FD80',
			},
			secondary: {
				main: '#8A8D93',
				light: '##9C9FA4',
				dark: '#4D5056',
				contrast: '#FFFFFF',
				containedHover: '#777B82',
				outlinedHover: '',
				outlinedRestingHover: '',
			},
			info: {
				main: '#16B1FF',
				light: '#32BAFF',
				dark: '#0E71A3',
				contrast: '#FFFFFF',
				containedHover: '#139CE0',
				outlinedHover: '',
				outlinedRestingHover: '',
			},
			success: {
				main: '#56CA00',
				light: '#6AD01F',
				dark: '#378100',
				contrast: '#FFFFFF',
				containedHover: '#4CB200',
				outlinedHover: '',
				outlinedRestingHover: '',
			},
			warning: {
				main: '#FFB400',
				light: '#FFB547',
				dark: '#A37300',
				contrast: '#FFFFFF',
				containedHover: '#E09E00',
				outlinedHover: '',
				outlinedRestingHover: '',
			},
			error: {
				main: '#FF4C51',
				light: '#FF6166',
				dark: '#A33134',
				contrast: '#FFFFFF',
				containedHover: '#E04347',
				outlinedHover: '',
				outlinedRestingHover: '',
			},
			text: {
				primary: 'rgba(58, 53, 65, 0.87)',
				secondary: '',
				disabled: '',
			},
			action: {
				active: '',
				hover: '',
				selected: '',
				disabled: '',
				disabledBg: '',
				focus: '',
			},
			other: {
				divider: '',
				outlineBorder: '',
				imputLine: '',
				snackBarBg: '',
				bodyBg: '#F4F5FA',
				paperCard: '',
			},
			custom: {
				primary: '',
				secondary: '',
				info: '',
				success: '',
				warning: '',
				error: '',
				menuActive: '',
			},
		},
	},
	dark: {
		colors: {
			primary: {
				main: '#',
				light: '#',
				dark: '#',
				contrast: '#',
				containedHover: '#',
				outlinedHover: '#',
				outlinedRestingHover: '#',
			},
			secondary: {
				main: '',
				light: '',
				dark: '',
				contrast: '',
				containedHover: '',
				outlinedHover: '',
				outlinedRestingHover: '',
			},
			info: {
				main: '',
				light: '',
				dark: '',
				contrast: '',
				containedHover: '',
				outlinedHover: '',
				outlinedRestingHover: '',
			},
			success: {
				main: '',
				light: '',
				dark: '',
				contrast: '',
				containedHover: '',
				outlinedHover: '',
				outlinedRestingHover: '',
			},
			warning: {
				main: '',
				light: '',
				dark: '',
				contrast: '',
				containedHover: '',
				outlinedHover: '',
				outlinedRestingHover: '',
			},
			error: {
				main: '',
				light: '',
				dark: '',
				contrast: '',
				containedHover: '',
				outlinedHover: '',
				outlinedRestingHover: '',
			},
			text: {
				primary: 'rgba(231, 227, 252, 0.87)',
				secondary: '',
				disabled: '',
			},
			action: {
				active: '',
				hover: '',
				selected: '',
				disabled: '',
				disabledBg: '',
				focus: '',
			},
			other: {
				divider: '',
				outlineBorder: '',
				imputLine: '',
				snackBarBg: '',
				bodyBg: 'linear-gradient(0deg, #28243D, #28243D), linear-gradient(0deg, #000000, #000000)',
				paperCard: '',
			},
			custom: {
				primary: '',
				secondary: '',
				info: '',
				success: '',
				warning: '',
				error: '',
				menuActive: '',
			},
		},
	},
};
