import { Dispatch, SetStateAction, useState } from 'react';
import { CreateBracketInputsT, TemplateTypeT } from '../types';
import { useMutation, useQuery } from 'react-query';
import { api } from '../../../api';
import { SubmitHandler } from 'react-hook-form';
import { v4 as uuidv4 } from 'uuid';
import { getAutogenerateData } from 'services/autogenerate';
import { IBracket } from 'interfaces/bracket.interface';
import { useNavigate } from 'react-router-dom';
import { BracketSorter } from 'services/BracketSort';

type OptionT = { id: string; label: string };

type useCreateBracketResult = {
	templateType: TemplateTypeT;
	setTemplateType: Dispatch<SetStateAction<TemplateTypeT>>;
	isMakeDuplicate: boolean;
	setIsMakeDuplicate: Dispatch<SetStateAction<boolean>>;
	brackets: OptionT[];
	submitHandler: SubmitHandler<CreateBracketInputsT>;
};

export const useCreateBracket = (): useCreateBracketResult => {
	const [templateType, setTemplateType] = useState<TemplateTypeT>('new_bracket');
	const [isMakeDuplicate, setIsMakeDuplicate] = useState(false);
	const [brackets, setBrackets] = useState<OptionT[]>([]);
	const navigate = useNavigate();

	useQuery('brackets', () => api.fetchBrackets(), {
		select: (data) => {
			return data.map((bracket) => ({ id: bracket.id, label: bracket.name }));
		},
		onSuccess: (data) => {
			setBrackets(data);
		},
	});

	const createBracketMutation = useMutation((bracket: Omit<IBracket, 'id'>) => api.createBracket(bracket), {
		onSuccess: (bracket) => {
			navigate(`/brackets/${bracket.id}`);
		},
	});

	const submitHandler: SubmitHandler<CreateBracketInputsT> = (data) => {
		if (templateType === 'new_bracket') {
			const { isThirdPlace, isFifthPlace, isHigherSeedsTeamsLogic, isRightSide, countOfTeams, bracketName } = data;

			const arrayOfLoserMatches = [isThirdPlace ? 3 : null, isFifthPlace ? 5 : null].filter(Boolean) as number[];

			const { rounds, matches, loserColumns } = getAutogenerateData(Number(countOfTeams), arrayOfLoserMatches, true);

			const bracketSorter = new BracketSorter({ matches, numTeams: Number(countOfTeams) });

			const generatedBracket = {
				id: uuidv4(),
				name: bracketName,
				created_at: Date.now(),
				updated_at: Date.now(),
				columns: rounds.concat(loserColumns),
				matches: bracketSorter.sortBracket(),
				isLoser3dMatch: isThirdPlace,
				isLoser5dMatch: isFifthPlace,
				isHigherSeedsTeamsLogic: isHigherSeedsTeamsLogic,
				cancelationMatchesAreRight: isRightSide,
			};
			createBracketMutation.mutate(generatedBracket);
		}
		if (templateType === 'saved_brackets') {
		}
	};

	return {
		templateType,
		setTemplateType,
		isMakeDuplicate,
		setIsMakeDuplicate,
		brackets,
		submitHandler,
	};
};
