export type TemplateT =  'custom' | 'autogenerate';

export type GenerateBracketDataT = {
	template: TemplateT;
	customModel: string,
	autoGeneratedNumberOfTeams?: number;
	bracketName: string
	duplicateName?: string,
	isLoser3dMatch?: boolean,
	isLoser5dMatch?: boolean,
	isHigherSeedsTeamsLogic?: boolean,
	cancelationMatchesAreRight?: boolean,
};
